version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    container_name: booking_home
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  db-data: