databases:
  - name: booking_home
    databaseName: booking_home_production
    user: booking_home
    plan: free

services:
  - type: web
    name: booking_home
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/rails db:migrate db:seed" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booking_home
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4